---
- name: Install python2 on Ubuntu 16.04
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
    # action: setup will gather facts after python2 has been installed
    - action: setup

- name: Deploys the User Information
  hosts: all
  become: true

  vars_files:
    - vars/user_list.yaml

  roles:
    - manage_users
